### ISSUE TITLE
Visualize Item Description Features and Clusters 

### ISSUE THREAD

**Issue by jinchen1036** [DSEI21000-S21/project-product-price-prediction#13]
**Describe the ticket: Explore the column `brand_name ` in the sample dataset**
- [ ] Cluster the extracted feature of Item Description 
- [ ] Visualize the cluster

**Describe the acceptance criteria of the ticket:**

- have a visualization

**Additional context:**

- [Embedding Projector] (https://projector.tensorflow.org/)

**Describe any relations and dependencies:**

- Related issue: #11

**Comment by zhiyingzhu1995** [comment]
tried pca and visualize them in TSNE
