### ISSUE TITLE
Feature Selection & Explore Regression Model for Predict Price

### ISSUE THREAD

**Issue by jinchen1036** [DSEI21000-S21/project-product-price-prediction#21]
**Describe the ticket: **
- [x] Explore different regression models for price prediction
- [ ] Use different features input to model
- [x] Select the important features
- [x] Compare the model performance (RMSE, RMSLLE)

**Describe the acceptance criteria of the ticket:**

- have the function written in final folder

**Additional context:**

**Describe any relations and dependencies:**

**Comment by ZhiLi51** [comment]
Question: curious about how you selected stopwords during the tokenizing process.  if by any chance, improving stopword selection could reduce the feature dimensions?
